[package]
name = "uo"
version = "0.1.0"
edition = "2021"
authors = ["Giuseppe Alberto Parisi <parisialberto@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
rand = "0.8.5"